spring:
  datasource:
    url: jdbc:mysql://localhost:3306/web?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
#整合mybatils
mybatis:
  type-aliases-package: com.example.springbootdatamybatils.Prjo
  mapper-locations: classpath:mybatis/mapperr/*.xml
